### PR TITLE
#20 split server.py into different folders and files

### LINKED ISSUE #20: Refactor the backend into multiple files

### PR DESCRIPTION
**Pull request by wumbus**
# What has been done
- The server.py had gotten way to big, I split it into multiple files

image

- server.py now only contains the initialization of the app, and its connections with the db, api and swagger
- the database folder includes setup for the database and the database models/tables
- In the folder resource_api  you have one file for User Resourceses, and one file for University resources, one file for the routing and one for the seralization fields definitions

### CODE REVIEW

**Review by tientrinh21 — CHANGES_REQUESTED** [review]
Looks pretty good for me, but let's remove the pycache from the repo.
I'll will wait for the changes as well as @seoykwon 's review by this Sunday, and I'll merge it.

**Comment by seoykwon** [comment]
Looks nice to me as well. Splitting the server.py would enhance the readability of the codes overall.

**Review by seoykwon — APPROVED** [review]

**Review by seoykwon — APPROVED** [review]

**Comment by tientrinh21** [comment]
@seoykwon I personally think that we should not specify the name for every .pyc file like [f8a0ed0](https://github.com/tientrinh21/uni-pov-exchange/pull/21/commits/f8a0ed0fd7e1b37a1ab949892347abb6e522d8f2).

Later, when the backend expands, adding more like this would not be a good choice, there should be way to tackle not to a specific folder, but for every .pyc files in the repo.

**Comment by tientrinh21** [comment]
@seoykwon @wumbus I did the thing, so feel free to double-check and I'll merge tomorrow.

**Comment by seoykwon** [comment]
Yeah, I agree of not using specific filenames to hide them. Seems nice!

**Review by seoykwon — APPROVED** [review]

**Review by tientrinh21 — APPROVED** [review]
Nice, let's merge

**Pull request merged**
